language: generic

os: linux

sudo: required

services:
  - docker

before_install:
  - docker pull pheymann/idris-travis:test

script:
  - docker run -v $(pwd):/var/idris-project pheymann/idris-travis:test ./project --testCI
