dist: trusty
sudo: required

language: generic

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install cabal-install
  - cabal update
  - cabal install idris
  - PATH=$HOME/.cabal/bin:$PATH

script:
  - ./project --testCI
